#!/usr/bin/bash

if [[ -z "$1" || $1 = "test" || $1 = "input"  ]]
then
    day=$(ls days | sort | tail -1)
    input=$1
else
    day="day-$1"
    input="$2"
fi

go run days/$day/main.go < days/$day/$input
